# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: IfNotPresent
  repository: gitlab-registry.in2p3.fr/astrolabsoftware/fink
  name: fink-alert-simulator
  tag: "v3.1.3-rc1"

kafka:
  socket: "kafka-cluster-kafka-bootstrap.kafka:9092"
  # TODO check that topic exists before sending alerts
  topic: "ztf_public_20200101"
