bases:
- ../../base/configmap

configMapGenerator:
- name: fink-alert-simulator
  behavior: replace
  files:
  - fink_alert_simulator.conf 
generatorOptions:
  labels:
    kustomize.generated.resources: fink.alert-simulator
  disableNameSuffixHash: true
