apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: fink-alert-simulator-
spec:
  entrypoint: main
  templates:
  - name: main
    volumes:
      - name: datasim
        emptyDir: {}
      - name: config
        configMap:
          name: fink-alert-simulator
    containerSet:
      volumeMounts:
        - mountPath: /datasim
          name: datasim
      containers:
        - name: download
          image: "{{workflow.parameters.image}}"
          command: ["download_datasim.sh"]
        - name: main
          image: "{{workflow.parameters.image}}"
          command: ["fink_simulator"]
          args: ["-c", "/config/fink_alert_simulator.conf"]
          volumeMounts:
          - name: config
            mountPath: /config
          dependencies:
            - download
